FROM golang:1.22-alpine
RUN apk add --no-cache git
WORKDIR /app

RUN git clone https://github.com/taksug229/Stock-Analysis.git
WORKDIR /app/Stock-Analysis
RUN go mod tidy
RUN chmod +x data_ingest_bg.sh

CMD ["sh", "-c", "go run getData.go && ./data_ingest_bg.sh"]
