version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - backend_data:/app/data

  mlmodel:
    build:
      context: .
      dockerfile: Dockerfile.mlmodel
    container_name: mlmodel
    depends_on:
      backend:
        condition: service_completed_successfully
    volumes:
      - backend_data:/app/data

volumes:
  backend_data:
